version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    #image: gordon/get-started:part2
    #image: hub.c.163.com/yemiancheng/friendlyhello:part-2
    image: 192.168.99.100:5000/friendlyhello
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: